<../../../mkconfig
<../mkconfig
MKSHELL = rc
all:VQ: 
	echo -n
install:V:
	mkdir -p $MAN/^(1 2 3 4 5 6 7 8)
	for(d in man/*)
		for(f in $d/*){
			cp -f $f $MAN/^`{basename $d}^/^`{basename $f}
			chmod 0644 $MAN^/^`{basename $d}^/^`{basename $f}
		}
clean:VQ:
	echo -n
