<mkconfig
HDR = `{ls *.h}
SRC = `{ls *.c}
OBJ = ${SRC:%.c=%.o}
TGT = $NAME
all :V: $TGT 
strip :V: $TGT
	$STRIP $TGT
$TGT : $OBJ
	$LD -o $TGT $LDFLAGS $OBJ $SLIB $LIB
%.o :V: %.c
	$CC -c -o $target $CFLAGS $prereq
%.c :N: $HDR
%.h :N:
clean :V:
	rm -rf $TGT *.o
install :V: $TGT
	cp -f $TGT $EXE/
	chmod 0755 $EXE/$TGT
uninstall :V:
	rm -f $EXE/$TGT
