<mkconfig
#HDR = `{ls *.h}
SRC = `{ls *.c}
OBJ = ${SRC:%.c=%.o}
TGT=$NAME.a
all install :V: $TGT
uninstall :V:
$TGT : $OBJ
	$AR $ARFLAGS $TGT $OBJ
%.o : %.c
	$CC -c -o $target $CFLAGS  $prereq
%.c :Q: $HDR
	touch $target
%.h :Q:
	touch $target
clean:
	rm -f $OBJ $TGT
