<mkconfig
<../mk/inc/cbuild
MKSHELL = rc
test:V: $TGT
	startx $HOME/lib/xinitrc ./$TGT
install : $TGT
	cp -f $TGT $SCRIPT $EXE/
	chmod 0755 $EXE/^($TGT $SCRIPT)
uninstall: 
	rm -f $EXE/$TGT
clean :
	rm -rf $TGT *.o 

