<mkconfig
<../mk/inc/cbuild
MKSHELL = rc
install : $TGT
	cp -f $TGT $SCRIPT $EXE/
	chmod 0755 $EXE/^($TGT $SCRIPT)
	cp -f man $MAN/1/$NAME
	chmod 0644 $MAN/1/$NAME
uninstall: 
	rm -f $EXE/^($TGT xemb)
clean :
	rm -rf $TGT *.o 

