<mkconfig
MKSHELL = sh
SYN = syn.y
HFILES = `{ls *.h}
CFILES = code.c exec.c getflags.c glob.c here.c io.c lex.c \
	pcmd.c pfnc.c simple.c subr.c trap.c tree.c unixcrap.c \
	var.c y.tab.c plan9ish.c havefork.c
OFILES = ${CFILES:%.c=%.o} $OBJ9
TARG = $PROGNAME
all :V: $TARG
strip :V: $TARG
	$STRIP $TARG
$TARG : x.tab.h $OFILES
	$LD -o $target $LDFLAGS $OFILES
%.o : %.c
	$CC -c -o $target $CPPFLAGS $CFLAGS $stem.c
%.c :NQ: $HDR x.tab.h
	touch $target
%.h :NQ:
x.tab.h: y.tab.h
	cp y.tab.h x.tab.h
y.tab.h: $SYN
	$YACC -d $SYN
clean :V:
	rm -rf $TARG *.o y.tab.c y.tab.h x.tab.h
install :V: $TARG strip
	mkdir -p $EXEDIR $APPDIR/$PROGNAME
	cp -f $TARG $EXEDIR/
	chmod 0755 $EXEDIR/$TARG
	rm -f $EXEDIR/rc
	ln -s $EXEDIR/$TARG $EXEDIR/rc
	cp man $MANDIR/1/$PROGNAME
	cp -f rcmain $APPDIR/$PROGNAME
uninstall :V:
	rm -f $EXEDIR/$TARG
