<mkconfig
SRC = `{ls *.c} $OBJ9
<$ROOT/mk/inc/cbuild
clean :V:
	rm -rf $TGT *.o
install :V: $TGT strip
	mkdir -p $EXE $APP/$NAME
	cp -f $TGT $EXE/
	cp -f par pars $APP/$NAME/
	chmod 0755 $EXE/$TGT
uninstall :V:
	rm -f $EXE/$TGT

