<mkconfig
SRC = `{ls *.c}
OBJ = $PATH9/lib9.a
<../mk/inc/cbuild
clean :V:
	rm -rf $TGT *.o
install :V: $TGT strip
	mkdir -p $EXE $MAN/1
	cp -f $TGT $EXE/$TGT
	cp -f man $MAN/1/$TGT
	chmod 0755 $EXE/$TGT
uninstall :V:
	rm -f $EXE/$TGT
