<mkconfig
SRC = `{ls *.c}
HDR = `{ls *.h}
<../../mk/inc/cbuild
install : $TGT
	mkdir -p $EXE $MAN/1
	cp -f $TGT $EXE/
	chmod 0755 $EXE/$TGT
	cp -f man $MAN/1/$TGT
	chmod 0644 $MAN/1/$TGT
uninstall: 
	rm -rf $EXE/$TGT
clean :
	rm -rf $TGT *.o 

