<mkconfig
MKSHELL = rc
#HDR = `{ls *.h}
SRC = `{ls *.c}
OBJ = ${SRC:%.c=%.o} $OBJ9
TGT = $NAME
CFLAGS = $CPPFLAGS
all :V: $TGT 
strip :V: $TGT
	$STRIP $TGT
$TGT : $OBJ
	$LD -o $target $LDFLAGS $OBJ
%.o :V: %.c
	$CC -c -o $target $CFLAGS $stem.c
%.c :QN: $HDR
%.h :QN:
clean :V:
	rm -rf $TGT *.o
install :V: $TGT strip
	mkdir -p $EXE $MAN/1
	cp -f $TGT $SCRIPT $EXE/
	cp -f man $MAN/1/$TGT
	chmod 0755 $EXE/^($TGT $SCRIPT)
uninstall :V:
	rm -f $EXE/$TGT
