<mkconfig
#HDR = `{ls *.h}
SRC = `{ls *.c}
OBJ = ${SRC:%.c=%.o}
TGT = $NAME
all :Q: $TGT 
	echo -n
strip :V: $TGT
	$STRIP $TGT
$TGT : $OBJ
	$LD -o $target $LDFLAGS $OBJ $LIB
%.o :V: %.c
	$CC -c -o $target $CPPFLAGS $CFLAGS $stem.c
%.c :Q: $HDR
	touch -c $target
%.h :Q:
	touch -c $target
clean :V:
	rm -rf $TGT *.o
install :V: $TGT strip
	mkdir -p $BIN $MAN/1
	cp -f $TGT $BIN/$TGT
	cp -f man $MAN/1/$TGT
	chmod 0755 $BIN/$TGT
uninstall :V:
	rm -f $BIN/$TGT
