<mkconfig
SRC = `{ ls *.c }
#HDR = `{ ls *.h }
<$APP/mk/inc/cbuild
install : $TGT
	mkdir -p $EXE $MAN/1
	cp -f $TGT $EXE
	chmod 0755 $EXE/$TGT 
	cp -f man $MAN/1/$NAME
	chmod 0644 $MAN/1/$NAME
uninstall: 
	rm -f $EXE/$TGT
clean :
	rm -rf $TGT *.o 
